#!/usr/bin/env bun
/**
 * Embeds the Latin subset of every catalog family into src/fonts/data.generated.ts.
 * Run after changing FONT_FAMILIES: `bun scripts/bundle-fonts.ts`.
 */
import { writeFileSync } from 'node:fs'
import { FONT_FAMILIES } from '../src/fonts/catalog'

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36'
const name = (family: string) => encodeURIComponent(family).replace(/%20/g, '+')
async function css(family: string): Promise<string> {
  for (const axis of [':wght@400..700', ':wght@400;700', '']) {
    const response = await fetch(`https://fonts.googleapis.com/css2?family=${name(family)}${axis}&display=swap`, { headers: { 'user-agent': UA } })
    if (response.ok) return response.text()
  }
  throw new Error(`Google Fonts has no ${family}`)
}

const faces: { family: string; weight: string; data: string }[] = []
let bytes = 0
for (const family of FONT_FAMILIES) {
  const sheet = await css(family)
  const seen = new Set<string>()
  // Each block is preceded by its subset comment; keep only latin.
  for (const block of sheet.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)) {
    if (block[1] !== 'latin') continue
    const url = block[2].match(/url\((https:[^)]+)\)/)?.[1]
    const weight = block[2].match(/font-weight:\s*([^;]+);/)?.[1].trim() ?? '400'
    if (!url || seen.has(url)) continue
    seen.add(url)
    const file = new Uint8Array(await (await fetch(url)).arrayBuffer())
    bytes += file.length
    faces.push({ family, weight, data: Buffer.from(file).toString('base64') })
  }
  if (!seen.size) throw new Error(`No latin subset for ${family}`)
  console.log(family, [...faces.filter((f) => f.family === family).map((f) => f.weight)].join(' | '))
}
const body = faces.map((f) => `  { family: ${JSON.stringify(f.family)}, weight: ${JSON.stringify(f.weight)}, data: ${JSON.stringify(f.data)} },`).join('\n')
writeFileSync('src/fonts/data.generated.ts', `// Generated by scripts/bundle-fonts.ts from Google Fonts (SIL Open Font License). Do not edit.\nexport const BUNDLED_FACES: { family: string; weight: string; data: string }[] = [\n${body}\n]\n`)
console.log(`${faces.length} faces, ${(bytes / 1024).toFixed(0)} KB woff2`)
